services:
  classifier:
    build:
      context: ./classifier
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1G
    volumes:
      - .:/app