services:
  classifier:
    build:
      context: ./classifier
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
        reservations:
          cpus: '2'
          memory: 1G
    volumes:
      - .:/app