services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - backend-network
    restart: always

  classifier:
    build:
      context: ./classifier
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1.5G
        reservations:
          cpus: '1'
          memory: 1G
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - WORKERS=8
      - THREADS=4
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - backend-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CLASSIFIER_URL=http://classifier:8000
      - GEMINI_API_BASE_URL=${GEMINI_API_BASE_URL:-https://generativelanguage.googleapis.com/v1beta/models}
      - REDIS_URL=redis://redis:6379
      - GOMAXPROCS=2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - backend-network
    restart: always
    depends_on:
      - redis

  payment:
    build:
      context: ./payment
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - GIN_MODE=release
      - DYNAMO_TABLE=${DYNAMO_TABLE:-subscriptions}
      - LSZ_API_KEY=${LSZ_API_KEY}
      - LSZ_WEBHOOK_SECRET=${LSZ_WEBHOOK_SECRET}
      - LSZ_STORE_ID=${LSZ_STORE_ID}
      - LSZ_REDIRECT_URL=${LSZ_REDIRECT_URL}
      - LSZ_RECEIPT_URL=${LSZ_RECEIPT_URL}
      - FIREBASE_SERVICE_ACCOUNT_PATH=${FIREBASE_SERVICE_ACCOUNT_PATH}
      - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    networks:
      - backend-network
    restart: always

volumes:
  redis_data:
    driver: local

networks:
  backend-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
