services:
  classifier:
    build:
      context: ./classifier
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - WORKERS=8
      - THREADS=4
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    networks:
      - backend-network

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - CLASSIFIER_URL=http://classifier:8000
      - OLLAMA_URL=http://host.docker.internal:11434
      - GEMINI_API_KEY=${GEMINI_API_KEY:-AIzaSyBsCZnxc5sI7SgKslUjXd5BCH65eZS4CSY}
      - GEMINI_MODEL_NAME=${GEMINI_MODEL_NAME:-gemini-2.0-flash-exp}
      - GEMINI_API_BASE_URL=${GEMINI_API_BASE_URL:-https://generativelanguage.googleapis.com/v1beta/models}
      - GOMAXPROCS=2
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 512M
    networks:
      - backend-network
    restart: always

networks:
  backend-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500
